name: auto_form_builder
description: "A Flutter package for dynamic forms with wizards, conditional fields, computed values, input masking, validation, and draft saving."
version: 1.0.0
homepage: https://nocorps.org/
repository: https://github.com/KANAGARAJ-M/auto_form_builder
issue_tracker: https://github.com/KANAGARAJ-M/auto_form_builder/issues

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
